framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
        missing_import_mode: strict
        importmap_polyfill: false

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
